[project]
name = "mshtbot"
version = "0.1.0"
description = "Meshtastic bot scripts"
authors = ["!!Dean <dwhall256@gmail.com>"]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "meshtastic>=2.3",
    "ollama>=0.5",
    "pubsub>=0.1",
]
